
services:
  frontend:
    build: ./frontend
    container_name: pg-frontend
    ports:
      - "3000:80"
    command: npm run dev
    networks:
      - my_network
    volumes:
      - my_volume:/app/cache 

  backend:
    build: ./backend
    container_name: pg-backend
    ports:
      - "5002:5000"
    command: npm start
    networks:
      - my_network
    volumes:
      - my_volume:/app/data   # ✅ SAFE location

networks:
  my_network:
    external: true

volumes:
  my_volume:
    external: true