name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Build backend
      - name: Build Backend Image
        run: docker build -t backend ./backend

      # 3. Build frontend
      - name: Build Frontend Image
        run: docker build -t frontend ./frontend

      # 4. Run backend (optional test)
      - name: Run Backend Container
        run: docker run -d -p 5000:5000 backend